/// Flutter icons SpentAllIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpentAllIcons
///      fonts:
///       - asset: fonts/SpentAllIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpentAllIcons {
  SpentAllIcons._();

  static const _kFontFam = 'SpentAllIcons';
  static const _kFontPkg = null;

  static const IconData analytics = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
